services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/melodyFlow/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    ports:
      - 127.0.0.1:5432:5432
